### ISSUE TITLE
Preparing message can lead to performance degradation

### ISSUE THREAD

**Issue by mal** [jdanbrown/minlog-slf4j#2]
Related to https://github.com/twitter/chill/issues/291#issuecomment-300423877

The current implemention of `Logger.log` unconditionally builds a string before dispatching it to an `slf4j` logging method. In applications where there is heavy use of the `DEBUG` (or indeed any) level this can seriously impact performance.

In the linked issue it is https://github.com/EsotericSoftware/kryo that makes copious use of the `DEBUG` level, expecting to be used in production with a "[fixed logging level of `NONE`](https://github.com/EsotericSoftware/kryo#logging)". This is not always possible if another dependency is using `minlog` to provide higher level messages.

Would it be possible to check the SLF4J logging level prior to rendering and dispatching the message?

**Comment by mal** [comment]
Alas, I've just seen your comment on #1 regarding not being the maintainer. Nevermind, I'll have to seek out an alternative.

**Comment by jdanbrown** [comment]
👍 Yep, I'm not a maintainer, and also I haven't been using this for a while. Do feel free to add more notes here if you find a good solution for others down the road.
